name: utils
description: An collection with Functional utils and some data structures
version: 3.0.3
homepage: https://github.com/kalildev/utils

environment:
  sdk: '>=2.16.0-0.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  collection:
  adt_annotation: ^3.0.0

dev_dependencies:
  adt_generator: ^3.0.0
  build_runner:
  demostudo_lint: ^1.0.0
  test: ^1.14.4
