name: utils
description: An collection with Functional utils and some data structures
version: 1.2.0
homepage: https://github.com/kalildev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.2.4 

dev_dependencies:
  demostudo_lint: ^1.0.0
  test: ^1.14.4