name: utils
description: An collection with Functional utils and some data structures
version: 2.1.0
homepage: https://github.com/kalildev

environment:
  sdk: '>=2.16.0-0.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  collection:
  adt_annotation:

dev_dependencies:
  adt_generator: ^1.2.2
  build_runner:
  demostudo_lint: ^1.0.0
  test: ^1.14.4
